# Title: Makefile(VC)
# ID: Textus-balance-Makefile-vc
# Build: B01:created by octerboy 2006/05/28, Gaungzhou
include ..\Rules.basemod.vc
CFLAGS  =  $(CFLAGS) -I..\baselib\include -I..\logdata\include
AMOROBJS=Balance.obj 

all: balance.dll

Balance.obj: Balance.cpp
	$(CC) $(CFLAGS) -DNNDEBUG -DAMOR_CLS_TYPE=Balance Balance.cpp

balance.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
