# Title: Makefile(VC)
# ID: Textus-Version-Makefile-vc
# Build: B01:created by octerboy 2006/05/28, Panyu in Gaungzhou

include ..\Rules.basemod.vc
AMOROBJS=Version.obj 

all: tversion.dll

Version.obj: Version.cpp
	$(CC) $(CFLAGS) -DNDEBUG -DAMOR_CLS_TYPE=Version Version.cpp

tversion.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
