# Title: Makefile(VC)
# ID: Textus-signal-Makefile-vc
# Build: B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
AMOROBJS=Signal.obj 

all: signal.dll

Signal.obj: Signal.cpp
	$(CC) $(CFLAGS) $(DEBUG_FLAG) -DAMOR_CLS_TYPE=Signal Signal.cpp

signal.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
