# Title: Makefile(VC)
# ID: Textus-trend-Makefile-vc
# Build:
#	B01:created by octerboy 2006/09/02, Panyu

include ..\Rules.basemod.vc
CFLAGS  = $(CFLAGS) -I..\baselib\include
LDLIB = ..\baselib\libbase.lib $(LDLIB)
AMOROBJS=Trend.obj 

all: trend.dll

Trend.obj: Trend.cpp
	$(CC) $(CFLAGS) -DNDEBUG -DAMOR_CLS_TYPE=Trend Trend.cpp

trend.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
