# Title: Makefile(VC)
# ID: Textus-Dummy-Makefile-vc
# Build: B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  =  $(CFLAGS) -I..\logdata\include
AMOROBJS=Dummy.obj 

all: dummy.dll

Dummy.obj: Dummy.cpp
	$(CC) $(CFLAGS) -DNNDEBUG -DAMOR_CLS_TYPE=Dummy Dummy.cpp

dummy.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
