# Title: Makefile(VC)
# ID: Textus-pmuto-Makefile-vc
# Build: 
#	B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  = $(CFLAGS) -I..\logdata\include 
AMOROBJS=Muto.obj 

all: pmuto.dll

Muto.obj: Muto.cpp
	$(CC) $(CFLAGS) -DNNDEBUG -DAMOR_CLS_TYPE=Muto Muto.cpp

pmuto.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
