# Title: Makefile(VC)
# ID: Textus-joint-Makefile-vc
# Build: 
#	B01:created by octerboy 2006/08/31, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  = $(CFLAGS) -I..\logdata\include 
AMOROBJS=Joint.obj 

all: joint.dll

Joint.obj: Joint.cpp
	$(CC) $(CFLAGS) -DNDEBUG -DAMOR_CLS_TYPE=Joint Joint.cpp

joint.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
