# Title: Makefile(VC)
# ID: Textus-ForkPro-Makefile-vc
# Build: B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  =  $(CFLAGS) -I..\logdata\include -I..\baselib\include
AMOROBJS=ForkPro.obj 

all: forkpro.dll

ForkPro.obj: ForkPro.cpp
	$(CC) $(CFLAGS) -DNNDEBUG -DAMOR_CLS_TYPE=ForkPro ForkPro.cpp

forkpro.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
        copy $@.* ..\release

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
