# Title: Makefile(VC)
# ID: Textus-keep-Makefile-vc
# Build: 
#	B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  = $(CFLAGS) -I..\logdata\include -I..\httpsrvhead\include
AMOROBJS=Keep.obj 

all: keep.dll

Keep.obj: Keep.cpp
	$(CC) $(CFLAGS) -DNNDEBUG -DAMOR_CLS_TYPE=Keep Keep.cpp

keep.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
