# Title: Makefile(VC)
# ID: Textus-pipe-Makefile-vc
# Build: 
#	B01:created by octerboy 2006/05/28, Gaungzhou

include ..\Rules.basemod.vc
CFLAGS  = $(CFLAGS) -I..\logdata\include 
AMOROBJS=Pipe.obj 

all: pipe.dll

Pipe.obj: Pipe.cpp
	$(CC) $(CFLAGS) $(DEBUG_FLAG) -DAMOR_CLS_TYPE=Pipe Pipe.cpp

pipe.dll: $(AMOROBJS)
	$(LD) $(LDFLAGS) -out:$@ $(AMOROBJS)  $(LDLIB)
	$(_VC_MANIFEST_PRO)
	$(_POST_RPO_SUB)

clean:
	del *.obj
	del *.dll.*
	del *.exp
	del *.lib
